stages:          
  - build
  - test

build_frontend:
  image: node
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

# test_frontend:
#   image: node
#   stage: test
#   script:
#     - cd frontend
#     - npm install
#     - npm test

test_backend:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - python3 backend/tests.py

# test_postman:
#   image: 
#     name: postman/newman:alpine
#     entrypoint: [""]
#   stage: test
#   script:
#     - cd backend
#     - newman --version
#     - newman run ../postman_jsons/Locations.postman_collection.json
#     - newman run ../postman_jsons/Farmers' Markets.postman_collection.json
#     - newman run ../postman_jsons/Nonprofits.postman_collection.json

test-postman:
  stage: test
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - newman run postman_jsons/Central Valley Farm Aid.postman_collection.json


# acceptance_tests:
#   image: python:3.10
#   stage: test
#   script:
#     - cd frontend
#     - pip install --upgrade pip
#     - pip install --no-cache-dir -r ./acceptance_tests/requirements.txt
#     - docker pull selenium/standalone-chrome
#     - docker run -dp 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
#     - python ./acceptance_tests/runTests.py

# gui-tests:
#     image: joyzoursky/python-chromedriver:3.9-selenium
#     stage: test
#     before_script:
#         - pip install -r requirements.txt
#     script:
#         - python3 src/gui-tests.py


# test_backend:
#   image: python:3
#   stage: test
#   before_script:
#     - pip install -r backend/requirements.txt
#   script:
#     - cd backend && python3 tests.py
