stages:          
  - build

build_frontend:
  image: node
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

# test_frontend:
#   image: node
#   stage: test
#   script:
#     - cd frontend
#     - npm install
#     - npm test

test_backend:
  image: python:3
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - cd backend && python3 tests.py

test_postman:
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  stage: test
  variables:
    POSTMAN_COLLECTION: "your_postman_collection_url_here"
  script:
    - cd backend
    - newman --version
    - newman run postman_collection.json